### ISSUE TITLE
Definitions within definitions not working

### ISSUE THREAD

**Issue by mdangear** [cmacclang/cmacc-lib-definitions#1]
The simple definitions work, but I get error messages when I have several definitions included in one definition:
>> cmacc DisclosingParty.cmacc test
(libuv) kqueue(): Too many open files
(libuv) kqueue(): Too many open files

It seems the system does not support having definitions within definitions

**Comment by wilmveel** [comment]
Referencing definitions for definitions was causing circular references in cmacc. Now you can reference a definitions without making an instance of the file.

previous:
$ disclosingParty = [./DisclosingParty.cmacc]

{{#definition disclosingParty}}

now:
{{#definition  [./DisclosingParty.cmacc]}}
